import { describe, expect, it } from "vitest";
import { computeSrcHash as tsComputeSrcHash, driftWarning, type SrcFileEntry } from "../src/utils/src-hash.js";
import { computeSrcHash as mjsComputeSrcHash, renderVersionFile } from "../scripts/gen-version.mjs";

// ---------------------------------------------------------------------------
// QW6: build-time version stamp + dist↔src drift banner.
//
// scripts/gen-version.mjs (plain Node, runs before `tsc` exists) and
// src/utils/src-hash.ts (compiled, imported by main.ts at runtime) duplicate the
// same content-hash algorithm rather than sharing it — see both files' headers
// for why. This suite proves the duplication hasn't drifted apart, that the
// hash is deterministic and file-order independent, that the drift comparator
// returns the right null/warning shape, and that the generated version.ts has
// the exact expected format.
// ---------------------------------------------------------------------------

const FIXTURE: SrcFileEntry[] = [
	{ relPath: "main.ts", content: "export const a = 1;\n" },
	{ relPath: "craft/state.ts", content: "export const b = 2;\n" },
	{ relPath: "statusbar/index.ts", content: "export const c = 3;\n" },
];

describe("computeSrcHash — determinism", () => {
	it("returns the same hash for the same input", () => {
		expect(tsComputeSrcHash(FIXTURE)).toBe(tsComputeSrcHash(FIXTURE));
	});

	it("is independent of input (filesystem enumeration) order", () => {
		const shuffled = [FIXTURE[2], FIXTURE[0], FIXTURE[1]];
		expect(tsComputeSrcHash(FIXTURE)).toBe(tsComputeSrcHash(shuffled));
	});

	it("changes when any file's content changes", () => {
		const mutated = FIXTURE.map(e => (e.relPath === "main.ts" ? { ...e, content: "export const a = 2;\n" } : e));
		expect(tsComputeSrcHash(FIXTURE)).not.toBe(tsComputeSrcHash(mutated));
	});

	it("changes when a file is added or removed", () => {
		const withExtra = [...FIXTURE, { relPath: "new.ts", content: "export const d = 4;\n" }];
		expect(tsComputeSrcHash(FIXTURE)).not.toBe(tsComputeSrcHash(withExtra));
	});

	it("returns a 12-character lowercase hex string", () => {
		expect(tsComputeSrcHash(FIXTURE)).toMatch(/^[0-9a-f]{12}$/);
	});
});

describe("computeSrcHash — gen-version.mjs / src-hash.ts parity", () => {
	it("both implementations produce identical output for the same input", () => {
		expect(mjsComputeSrcHash(FIXTURE)).toBe(tsComputeSrcHash(FIXTURE));
	});

	it("both implementations agree the hash is order-independent", () => {
		const shuffled = [FIXTURE[1], FIXTURE[2], FIXTURE[0]];
		expect(mjsComputeSrcHash(shuffled)).toBe(tsComputeSrcHash(FIXTURE));
	});

	it("both implementations agree on the empty-input hash", () => {
		expect(mjsComputeSrcHash([])).toBe(tsComputeSrcHash([]));
	});
});

describe("driftWarning", () => {
	it("returns null when the build-time and current src hashes match", () => {
		expect(driftWarning("abc123def456", "abc123def456")).toBeNull();
	});

	it("returns the stale-dist warning text when the hashes differ", () => {
		const warning = driftWarning("abc123def456", "000000000000");
		expect(warning).toBe("lets-craft: dist is stale (src has changed since last build) — run 'npm run build'");
	});
});

describe("renderVersionFile — generated version.ts format", () => {
	it("emits the exact expected BUILD_INFO module shape", () => {
		const content = renderVersionFile({ version: "0.1.0", gitHash: "abc1234", srcHash: "0123456789ab" });
		expect(content).toBe(
			[
				"// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.",
				"export const BUILD_INFO = {",
				'\tversion: "0.1.0",',
				'\tgitHash: "abc1234",',
				'\tsrcHash: "0123456789ab",',
				"} as const;",
				"",
			].join("\n"),
		);
	});

	it("JSON-escapes values so untrusted-looking content still parses as valid TS", () => {
		const content = renderVersionFile({ version: '1.0.0"; console.log("pwned', gitHash: "unknown", srcHash: "deadbeef0000" });
		expect(content).toContain('version: "1.0.0\\"; console.log(\\"pwned",');
	});
});
