#!/usr/bin/env node
// Build-time version + drift fingerprint generator (QW6). Runs BEFORE `tsc` (see
// package.json's `build` script: `node scripts/gen-version.mjs && tsc`), so it
// cannot import any compiled module. It writes `src/generated/version.ts` with
// the package version, the current git short hash (or "unknown" outside a git
// checkout), and a short content-hash of every `src/**/*.ts` file — the
// fingerprint `main.ts`'s session_start handler re-derives at runtime to warn
// when a loaded `dist/` is stale relative to `src/` (C-drift).
//
// The hash algorithm below is deliberately duplicated in src/utils/src-hash.ts
// for that runtime side rather than shared: this script runs before `tsc`
// produces anything under dist/, so it has no compiled module to import from.
// test/src-hash.test.ts asserts both implementations agree on the same input,
// so the duplication itself can't silently drift.
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const SRC_DIR = join(ROOT, "src");
const OUT_DIR = join(SRC_DIR, "generated");
const OUT_PATH = join(OUT_DIR, "version.ts");

// `src/generated/` is this script's own output (version.ts lives inside it) — excluded
// from its own input hash so the fingerprint never becomes self-referential across
// successive builds (see src/utils/src-hash.ts for the matching runtime-side exclusion).
const EXCLUDED_TOP_LEVEL_DIRS = new Set(["generated"]);

/** Recursively list every `.ts` file under `srcDir`, excluding `src/generated/`. */
function walkSrcTsFiles(srcDir) {
	const out = [];
	const stack = [srcDir];
	while (stack.length > 0) {
		const dir = stack.pop();
		if (!dir || !existsSync(dir)) continue;
		for (const entry of readdirSync(dir, { withFileTypes: true })) {
			if (entry.isDirectory() && dir === srcDir && EXCLUDED_TOP_LEVEL_DIRS.has(entry.name)) continue;
			const full = join(dir, entry.name);
			if (entry.isDirectory()) stack.push(full);
			else if (entry.isFile() && entry.name.endsWith(".ts")) out.push(full);
		}
	}
	return out;
}

function toPosixRelative(root, file) {
	return relative(root, file).split(sep).join("/");
}

function readSrcEntries(srcDir) {
	return walkSrcTsFiles(srcDir).map(file => ({ relPath: toPosixRelative(srcDir, file), content: readFileSync(file, "utf8") }));
}

/**
 * Deterministic short hash (first 12 hex chars of a SHA-256) over a set of source file
 * entries. Sorts by relPath first, so filesystem enumeration order never affects the
 * result (readdirSync order is not guaranteed across platforms/filesystems).
 */
export function computeSrcHash(entries) {
	const sorted = [...entries].sort((a, b) => (a.relPath < b.relPath ? -1 : a.relPath > b.relPath ? 1 : 0));
	const hash = createHash("sha256");
	for (const entry of sorted) {
		hash.update(entry.relPath);
		hash.update("\0");
		hash.update(entry.content);
		hash.update("\0");
	}
	return hash.digest("hex").slice(0, 12);
}

function resolveGitHash() {
	try {
		const out = execSync("git rev-parse --short HEAD", { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
		return out.length > 0 ? out : "unknown";
	} catch {
		return "unknown";
	}
}

/** Render `src/generated/version.ts`'s exact contents — also asserted verbatim by a unit test. */
export function renderVersionFile(info) {
	return `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
export const BUILD_INFO = {
	version: ${JSON.stringify(info.version)},
	gitHash: ${JSON.stringify(info.gitHash)},
	srcHash: ${JSON.stringify(info.srcHash)},
} as const;
`;
}

function main() {
	const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
	const srcHash = computeSrcHash(readSrcEntries(SRC_DIR));
	const gitHash = resolveGitHash();
	mkdirSync(OUT_DIR, { recursive: true });
	writeFileSync(OUT_PATH, renderVersionFile({ version: pkg.version, gitHash, srcHash }));
	console.log(`lets-craft: generated src/generated/version.ts (version=${pkg.version} git=${gitHash} srcHash=${srcHash})`);
}

const isMain = process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`;
if (isMain) main();
